// This file is normally auto-generated by `serverpod generate`.
// Run `serverpod generate` to regenerate after modifying model definitions.

import 'package:serverpod_client/serverpod_client.dart';

import 'task.dart';
import 'butler_response.dart';
import 'daily_briefing.dart';
import 'automation.dart';

export 'task.dart';
export 'butler_response.dart';
export 'daily_briefing.dart';
export 'automation.dart';
export 'client.dart';

class Protocol extends SerializationManager {
  static final Protocol _instance = Protocol._();

  Protocol._();

  factory Protocol() => _instance;

  @override
  T deserialize<T>(dynamic data, [Type? t]) {
    t ??= T;
    if (t == Task) {
      return Task.fromJson(data as Map<String, dynamic>, this) as T;
    }
    if (t == ButlerResponse) {
      return ButlerResponse.fromJson(data as Map<String, dynamic>, this) as T;
    }
    if (t == DailyBriefing) {
      return DailyBriefing.fromJson(data as Map<String, dynamic>, this) as T;
    }
    if (t == Automation) {
      return Automation.fromJson(data as Map<String, dynamic>, this) as T;
    }
    return super.deserialize<T>(data, t);
  }

  @override
  String? getClassNameForObject(Object data) {
    if (data is Task) return 'Task';
    if (data is ButlerResponse) return 'ButlerResponse';
    if (data is DailyBriefing) return 'DailyBriefing';
    if (data is Automation) return 'Automation';
    return super.getClassNameForObject(data);
  }

  @override
  dynamic deserializeByClassName(Map<String, dynamic> data) {
    if (data['className'] == 'Task') {
      return deserialize<Task>(data['data']);
    }
    if (data['className'] == 'ButlerResponse') {
      return deserialize<ButlerResponse>(data['data']);
    }
    if (data['className'] == 'DailyBriefing') {
      return deserialize<DailyBriefing>(data['data']);
    }
    if (data['className'] == 'Automation') {
      return deserialize<Automation>(data['data']);
    }
    return super.deserializeByClassName(data);
  }
}
