import 'package:serverpod/serverpod.dart';

/// A daily briefing generated by the Flutter Butler.
class DailyBriefing extends SerializableModel {
  String greeting;
  DateTime date;
  List<String> priorities;
  List<String> suggestions;
  String motivationalQuote;

  DailyBriefing({
    required this.greeting,
    required this.date,
    required this.priorities,
    required this.suggestions,
    required this.motivationalQuote,
  });

  factory DailyBriefing.fromJson(Map<String, dynamic> json) {
    return DailyBriefing(
      greeting: json['greeting'] as String,
      date: DateTime.parse(json['date'] as String),
      priorities: (json['priorities'] as List).cast<String>(),
      suggestions: (json['suggestions'] as List).cast<String>(),
      motivationalQuote: json['motivationalQuote'] as String,
    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
      'greeting': greeting,
      'date': date.toIso8601String(),
      'priorities': priorities,
      'suggestions': suggestions,
      'motivationalQuote': motivationalQuote,
    };
  }
}
